version: "3.9"

services:
  consul:
    image: bitnami/consul
    container_name: "consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"
    networks:
      - task-net

  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - task-net

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - task-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit-mq"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - task-net

  postgres:
    image: postgres:16.2
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=g8292gwjo
      - POSTGRES_DB=profit
    networks:
      - task-net

  song-service:
    container_name: "song-service"
    build:
      context: ./song-service
      dockerfile: Dockerfile
    ports:
      - "1003:1003"
    depends_on:
      - consul
      - rabbitmq
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/profit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=g8292gwjo
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_RABBITMQ_HOST=rabbit-mq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - task-net

#  mail-service:
#    container_name: "mail-service"
#    build:
#      context: ./service-mail-sender
#      dockerfile: Dockerfile
#    ports:
#      - "1001:1001"
#    depends_on:
#      - rabbitmq
#      - elasticsearch
#    environment:
#      - SPRING_CLOUD_CONSUL_HOST=consul
#      - SPRING_CLOUD_CONSUL_PORT=8500
#      - SPRING_RABBITMQ_HOST=rabbit-mq
#      - SPRING_RABBITMQ_PORT=5672
#      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9200
#    networks:
#      - task-net

networks:
  task-net:
    driver: bridge
